### PR TITLE
A few small edits, instructions for Homebrew, and a separate man page

### PR DESCRIPTION
**Pull request by chrisfinazzo**
An update to the Homebrew formula can be found [here].

[here]: https://github.com/Homebrew/homebrew-core/pull/137132

### CODE REVIEW

**Comment by sitkevij** [comment]
Please point to `develop` branch to be in line with upcoming changes and release candidate, thanks.

**Comment by chrisfinazzo** [comment]
> Please point to `develop` branch to be in line with upcoming changes and release candidate, thanks.

Would you prefer I push there? If so, I can add the remote...

**Comment by sitkevij** [comment]
Yes, thanks.

**Comment by chrisfinazzo** [comment]
See #76 for the revised PR.

**Pull request closed without merging**
